FROM docker0.unxs.io:5000/mariadb:dev
LABEL maintainer "UnxsIO Docker <docker@unxs.io>"

#Customize
COPY ./my_custom.cnf /bitnami/mariadb/conf/my_custom.cnf

#	docker build -t docker0.unxs.io:5000/mariadb2:dev .
#	docker push docker0.unxs.io:5000/mariadb2:dev
