version: '3.3'

services:
  
  #
  #
  #Docker visualizer start
  #
  viz:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - '32712:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
  
  #
  #Docker visualizer end
  #
  #
  
#How to use
#docker stack deploy --compose-file visual.yml visual
