version: '2'

services:

 nginx0:
  image: "nginx:alpine"
  ports:
   - "1812:1812/udp"
   - "1813:1813"
   - "18120:18120"

 freeradius0:
  image: "freeradius:dev"
  volumes:
   - "./clients.conf:/etc/raddb/clients.conf"
   - "./users:/etc/raddb/users"
    
 freeradius1:
  image: "freeradius:dev"
  volumes:
   - "./clients.conf:/etc/raddb/clients.conf"
   - "./users:/etc/raddb/users"

 freeradius-authtest:
  image: "freeradius:dev"
  command: "radtest testing password nginx0 0 SECRET"

 freeradius-accttest:
  image: "freeradius:dev"
  command: "radclient -f /etc/raddb/acct.start nginx0 acct SECRET"
  volumes:
   - "./acct.start:/etc/raddb/acct.start"
