version: '2'

services:

 mysql0:
  image: "mysqlfr:dev"
  volumes:
   - "/var/local/mysql0:/var/lib/mysql"

 freeradius0:
  image: "freeradius:dev"
  volumes:
   - "./clients.conf:/etc/raddb/clients.conf"
   - "./users:/etc/raddb/users"
  depends_on:
   - mysql0
    
 freeradius1:
  image: "freeradius:dev"
  volumes:
   - "./clients.conf:/etc/raddb/clients.conf"
   - "./users:/etc/raddb/users"
  depends_on:
   - mysql0

 nginx0:
  image: "nginxfr:dev"
  ports:
   - "1812:1812/udp"
   - "1813:1813"
  environment:
   - cUpstreamAuthServers=freeradius0:1812;freeradius1:1812
   - cUpstreamAcctServers=freeradius0:1813;freeradius1:1813
  depends_on:
   - freeradius0
   - freeradius1

 freeradius-authtest:
  image: "freeradius:dev"
  #command: "radtest testing password nginx0 0 SECRET"
  command: "radtest Sonar_1170982 AF745JB6L75P nginx0 0 SECRET"
  depends_on:
   - nginx0

 freeradius-accttest:
  image: "freeradius:dev"
  command: "radclient -f /etc/raddb/acct.start nginx0 acct SECRET"
  volumes:
   - "./acct.start:/etc/raddb/acct.start"
  depends_on:
   - nginx0
