version: '2'

services:

 nginx:
  image: "nginx:alpine"
  networks:
   mynet:
    ipv4_address: 172.25.0.10

 freeradius0:
  image: "freeradius:dev"
  ports:
   - "1812:1812/udp"
   - "1813:1813"
   - "18120:18120"
  volumes:
   - "./clients.conf:/etc/raddb/clients.conf"
   - "./users:/etc/raddb/users"
  networks:
   mynet:
    ipv4_address: 172.25.0.100
    
  freeradius1:
  image: "freeradius:dev"
  ports:
   - "1812:1812/udp"
   - "1813:1813"
   - "18120:18120"
  volumes:
   - "./clients.conf:/etc/raddb/clients.conf"
   - "./users:/etc/raddb/users"
  networks:
   mynet:
    ipv4_address: 172.25.0.101

 freeradius-test:
  image: "freeradius:dev"
  command: "radtest testing password freeradius0 0 SECRET"
  networks:
   mynet:
    ipv4_address: 172.25.0.101

networks:
  mynet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
